name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Esta vaga está sem updates há mais de 1 mês. Por favor feche-a caso não esteja mais disponível'
        stale-issue-label: 'no-issue-activity'
